plugins {
    id 'com.android.application'
}

android {
    namespace 'ru.unknows.vasiliev'
    compileSdk 34

    defaultConfig {
        applicationId "ru.unknows.vasiliev"
        
        minSdk 21
        
        targetSdk 34
        
        versionCode 43
        versionName "v3.0.43"
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }

    lint {
        checkReleaseBuilds false
        abortOnError false
    }
}
